Fix unescaped quote in Delegation scopeNote
The scopeNote for 'Delegation' used single quotes as the string
delimiter but contained an inner 'Delegation' in single quotes,
prematurely terminating the string and causing:
  SyntaxError: Unexpected identifier 'Delegation'

This broke the taxonomy-browser page, which parses the raw file via
new Function(). Switch the outer delimiter to double quotes.

Signed-off-by: Matthew Khouzam <matthew.khouzam@ericsson.com>